#!/bin/bash

ARCH="$(uname --machine)"

cd `dirname $0`
set -ve

if [ ! -f arduino-cli_0.13.0_Linux_ARM64.tar.gz ]; then
  wget https://github.com/arduino/arduino-cli/releases/download/0.13.0/arduino-cli_0.13.0_Linux_ARM64.tar.gz
fi
tar -xvf arduino-cli_0.13.0_Linux_ARM64.tar.gz -z arduino-cli && mv arduino-cli arduino-cli-aarch64

if [ ! -f arduino-cli_0.13.0_Linux_ARMv7.tar.gz ]; then
  wget https://github.com/arduino/arduino-cli/releases/download/0.13.0/arduino-cli_0.13.0_Linux_ARMv7.tar.gz
fi
tar -xvf arduino-cli_0.13.0_Linux_ARMv7.tar.gz -z arduino-cli && mv arduino-cli arduino-cli-armv7l

if [ ! -f arduino-cli_0.13.0_Linux_64bit.tar.gz ]; then
  wget https://github.com/arduino/arduino-cli/releases/download/0.13.0/arduino-cli_0.13.0_Linux_64bit.tar.gz
fi
tar -xvf arduino-cli_0.13.0_Linux_64bit.tar.gz -z arduino-cli && mv arduino-cli arduino-cli-x86_64

if [ ! -f arduino-cli_0.13.0_Linux_32bit.tar.gz ]; then
  wget https://github.com/arduino/arduino-cli/releases/download/0.13.0/arduino-cli_0.13.0_Linux_32bit.tar.gz
fi
tar -xvf arduino-cli_0.13.0_Linux_32bit.tar.gz -z arduino-cli && mv arduino-cli arduino-cli-i686

./run-arduino-cli core install arduino:avr@1.8.3

# Copy over patches to the Wire library to alternative architectures if they exist
if [ -d arduino-data-x86_64-dir ]; then
  if [ -d arduino-data-armv7l-dir ]; then
    cp arduino-data-x86_64-dir/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src/Wire.* arduino-data-armv7l-dir/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src/
  fi
  if [ -d arduino-data-aarch64-dir ]; then
    cp arduino-data-x86_64-dir/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src/Wire.* arduino-data-aarch64-dir/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src/
  fi
  if [ -d arduino-data-i686-dir ]; then
    cp arduino-data-x86_64-dir/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src/Wire.* arduino-data-i686-dir/packages/arduino/hardware/avr/1.8.3/libraries/Wire/src/
  fi
fi
