# The modem receiver must run on a 16 MHz atmega328p or the CPU isn't fast enough
# Use fastest baud rate possible to avoid adding delays to tight 4000 Hz loop timing
PORT=/dev/ttyACM0
BAUD=1000000
FQBN=arduino:avr:pro:cpu=16MHzatmega328
OPTIBOOT_BAUD=115200
